apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-00-a5eec4e3d6b5/my-repository/hello-cloudbuild:v1.0
        ports:
        - containerPort: 8080
